### ISSUE TITLE
Target Calculations  -FY19 OVC_HIVSTAT Share of OVC_SERV <18

### ISSUE THREAD

**Issue by shapaklyak** [achafetz/DataPack#101]
Target Calculation tab: Column GS - currently the formula points to OVC SERV "Other"  "M_ovc_oth_fy19"  instead of OVC HIV STAT in the **Assumption Input tab** Should it point to **"M_ovc_hivstat_share"** ? 

**Target calculation tab**
![image](https://user-images.githubusercontent.com/5234106/34176291-7b187d62-e4cd-11e7-8a15-ce537e983937.png)

**Assumption Tab**
![image](https://user-images.githubusercontent.com/5234106/34176351-a27c4406-e4cd-11e7-9d40-3e27f6e9ce8a.png)

**Comment by achafetz** [comment]
Yes indeed! Fixed!
