### ISSUE TITLE
Allocation by IM x SNU, PMTCT_ART

### ISSUE THREAD

**Issue by HosseiniPR** [achafetz/DataPack#104]
Columns U,V  PMTCT_ART, and PMTCT_ART Newly are not populated.

**Comment by HosseiniPR** [comment]
Also formatting doesn't seem to have gone all the way to the bottom.  Also PMTCT_ART already is not evenly divisible by 100%.

**Comment by HosseiniPR** [comment]
Some of the HTS_TST modalities also have 0 all the way down, but that might be because they did not happen in FY17.

**Comment by achafetz** [comment]
I think this is a result of the columns not being aligned. I've adjusted and will check again when I rerun the data pack tomorrow after more adjustments are made.
