### ISSUE TITLE
Allocation by SNUxIM - OVC SERV formulas flipped

### ISSUE THREAD

**Issue by shapaklyak** [achafetz/DataPack#106]
flip active & transferred

![image](https://user-images.githubusercontent.com/5234106/34177171-ab55033a-e4d0-11e7-9c45-7961659b0ead.png)

**Comment by shapaklyak** [comment]
same for econ & social protection

![image](https://user-images.githubusercontent.com/5234106/34177239-ed0cecf2-e4d0-11e7-8d8c-f2adc168a973.png)

**Comment by achafetz** [comment]
fixed for the allocation and target portions of the tab
