### ISSUE TITLE
Formatting Issue: Targeting Calculation Tab 

### ISSUE THREAD

**Issue by Bddamulira** [achafetz/DataPack#107]
Column CR 
FY19 TX_RET <15 displaying as a decimal 

--

**Comment by achafetz** [comment]
Duplicate of #109

**Comment by KTmonkey** [comment]
Hey, 

Target Calculation tab, Cols L, P, and BB all have decimal places.

**Comment by achafetz** [comment]
all intentional. just don't want decimals with non-percentages
