### ISSUE TITLE
DATIM Indicator Table- HTS_TST, Homa Bay

### ISSUE THREAD

**Issue by Yabayabadoo** [achafetz/DataPack#111]
Value mismatch btw BP & Pano/FACTVIEW
![image](https://user-images.githubusercontent.com/34660366/34177901-45f8609c-e4d3-11e7-8499-a7b582670d42.png)
![image](https://user-images.githubusercontent.com/34660366/34177914-537c5b74-e4d3-11e7-89bc-92719d91b38e.png)
![image](https://user-images.githubusercontent.com/34660366/34177950-67454df0-e4d3-11e7-9109-01a231165763.png)

**Comment by achafetz** [comment]
columns read in as int. cells with large data are being recorded as NA. solution is read in APR values as double.
```
fv_ouim <-read_tsv("~/ICPI/Data/ICPI_FactView_OU_IM_20171115_v1_1.txt",   
                   col_types = cols(FY2017APR = col_double()))
```
