### ISSUE TITLE
FY19 PMTCT_ART new vs already on ART Target Calc Tab (Col. BR, BS)

### ISSUE THREAD

**Issue by victoriadryan** [achafetz/DataPack#112]
We think the is a redundant portion of the formula for the FY19 target for PMTCT_ART new vs. already on ART disaggs, which could be removed - both in Col. BR and in Col. BS of the Target Calc tab. As it stands it is probably harmless to include but would simplify the formula if removed.

PMTCT_ART is auto-calculated from the sum of new vs already on disaggs and therefore PMTCT_ART "already on" can never be greater than the total PMTCT_ART. 
![image](https://user-images.githubusercontent.com/18488502/34178060-d7f3ca68-e4d3-11e7-961e-8029f575c47f.png)
![image](https://user-images.githubusercontent.com/18488502/34178088-ec9f9f5a-e4d3-11e7-849f-a849c443338f.png)

**Comment by achafetz** [comment]
Simplified!
