### ISSUE TITLE
Assumption Input tab, PMTCT_ART label (Col. AD) - change from _arv to _art

### ISSUE THREAD

**Issue by victoriadryan** [achafetz/DataPack#113]
Recommend changing the label for PMTCT_ART in Col AD on Assumption Input tab
Currently listed as M_pmtct_arv_T
Recommend changing to M_pmtct_art_T

(we no longer use PMTCT_ARV - this was a name change to the indicator for MER 2.0)

![image](https://user-images.githubusercontent.com/18488502/34178270-95ccbb26-e4d4-11e7-8540-4cd2df0e15e8.png)

**Comment by achafetz** [comment]
done!
