### ISSUE TITLE
OVC_SERV Updates

### ISSUE THREAD

**Issue by ClarkK-SGAC** [achafetz/DataPack#115]
Hi Aaron -

The OVC_SERV indicator is being updated as of 19-December. "Transferred" and "Exited without graduation" should no longer be included in the numerator total. Numerator should only include those OVCs that are active and those that the program plans to graduate. Targets should not be set for transferred or exited without graduation in COP 18. Let me know if you have any questions.

Best wishes,

Kristine

**Comment by achafetz** [comment]
are you around OGAC today? can we talk about target formulation today?

[2017.12.21 COP18 Data Pack OVC Change.pdf](https://github.com/achafetz/DataPack/files/1579542/2017.12.21.COP18.Data.Pack.OVC.Change.pdf)

**Comment by ClarkK-SGAC** [comment]
Hi Aaron - I am out of the office and offline today and tomorrow until around noon. I will be working from home tomorrow afternoon. We can have a call then or I will be back in the office on Tuesday next week. Let me know! 

Best wishes,

Kristine

**Comment by achafetz** [comment]
Moving forward with option 3
[2017.12.22 COP18 Data Pack OVC Change.pdf](https://github.com/achafetz/DataPack/files/1583320/2017.12.22.COP18.Data.Pack.OVC.Change.pdf)
