### ISSUE TITLE
@achafetz : Team Nigeria notes Inconsistencies with figures for same variable across tabs in Datapack

### ISSUE THREAD

**Issue by annakradin** [achafetz/DataPack#125]
Team Nigeria noted some inconsistencies with figures for the same variable across tables. The table below shows an example for PLHIV and Treatment. As you move across tabs, beginning with the DATIM Indicator tab, the number changes. We have presented some examples in the table below but think that they may be more. It will be helpful if ICPI can assist to check internal consistency across the tabs.  

From Kristin Roha: After looking into this further it appears to be due to the Data Pack having the Military SNU but it has not been populated by data throughout.  The team is manually populating their MIL data, but I wonder if any other OU’s have reported this issue.
 

Variable (all data without Military Nigeria data) | DATIM Indicator Table | Assumption Input | Target Calculation
-- | -- | -- | --
PLHIV | 2,878,063 | 2,896,544 | 2,896,544
FY17 CURR | 744,240 |   | 747,434
FY17 NEW | 918,228 |   | 919,083

![screen shot 2018-01-30 at 8 13 57 pm](https://user-images.githubusercontent.com/35980543/35600110-2ff4ea02-05fa-11e8-9188-596d21baf555.png)

**Comment by achafetz** [comment]
I don't have their old DP handy, but I'm looking at the version just populated (`v2018.02.02`) and I'm getting 100% match across all tabs for those indicators. This may have been a result of the prioritization issue that CIV flagged.

  | DATIM Indicator Table | Assumption Input | Target Calculation
-- | -- | -- | --
PLHIV | 2,878,063 | 2,878,063 | 2,878,063
FY17 CURR | 744,240 |   | 744,240
FY17 NEW | 158,845 |   | 158,845
