### ISSUE TITLE
NGA -> Suggested change to TX_NET NEW & LTFU

### ISSUE THREAD

**Issue by annakradin** [achafetz/DataPack#126]
FY19 TX_NET NEW in target calculation tab: The formula is IFERROR(MAX(0,AK7*(H7*AJ7-MAX(N7,AB7))),0) was used to calculate, which results in 0 for all LGA’s. We are suggesting the formula below for your consideration:
 
a)       PEPFAR’s Coverage of FY18 Unmet need*(PLHIV minus FY18 subnat TX_CURR Results)
 
![screen shot 2018-01-30 at 8 19 32 pm](https://user-images.githubusercontent.com/35980543/35600233-f71cc46a-05fa-11e8-957e-8ae2ff5a5e46.png)

![screen shot 2018-01-30 at 8 24 46 pm](https://user-images.githubusercontent.com/35980543/35600404-b4f32088-05fb-11e8-95e2-d26304dfdd6b.png)

**Comment by achafetz** [comment]
This may merit a discussion with @noahbartlett and others. The formula is correct, it's just that they likely haven't changed their ART coverage rate. 

The proposed calculation is looking a bit odd, since PLHIV burden would be cancelling out.

**Comment by achafetz** [comment]
Nigeria has to use different formulas due to their lower TX_CURR FY19 targets. Jamie and I reviewed with the team and are okay with the changes.
