### ISSUE TITLE
@achafetz : Team Nigeria Recommends revised formulas for FY19 TX_NET_NEW and FY19 LTFU in Target Calculation Tab

### ISSUE THREAD

**Issue by annakradin** [achafetz/DataPack#127]
![screen shot 2018-01-30 at 8 24 46 pm](https://user-images.githubusercontent.com/35980543/35600404-b4f32088-05fb-11e8-95e2-d26304dfdd6b.png)

**Comment by achafetz** [comment]
combining into 126
