### ISSUE TITLE
@achafetz: E Weathers identified potential errors with VMMC formulas (Assumption input & target calculation tabs)

### ISSUE THREAD

**Issue by annakradin** [achafetz/DataPack#128]
Ebonnie Weathers believes she has identified errors in VMMC formulas as follows:

Assumption Input
1. Coulumns AX and AY : Headings read "COP16 VMMC_CIRC Central Funding Target" and "COP16 VMMC_CIRC Central Funding Target, age 15-29"

CORRECTION: Should these actually say COP17 VMMC_CIRC Central Funding Target...?

Target Caluclation
1. In column EY "FY19 Target VMMC_CIRC,  age 15-29" , targets are calculated based on the coverage required for epidemic control, same as the overall VMMC targets, is this correct? In the case of Zambia, the coverage for the 15-29 group is already greater than the all ages VMMC coverage so many of the targets are coming up as zero.

2. In column EZ "FY18 Expected Coverage,  age 15-29", the  calculation divides the "Expected Cumulative Number of Circumcised Men  (end of FY18)" by the "Total male population, age 15-29" i.e. [=IFERROR(EU7/EN7,0)]

CORRECTION: =IFERROR(EV7/EN7,0) i.e. divide Expected Cumulative Number of Circumcised Men, age 15-29 (end of FY18) by the Total male population, age 15-29

3. In column FA "FY19 Target Coverage,  age 15-29", the calculation is [=IFERROR((EU7+EY7)/EN7,0)], once again using the "Expected Cumulative number of Circumcised Men (end of FY18)" instead of the " "Expected Cumulative number of Circumcised Men, 15-29 (end of FY18)". This formula adds the expected number of men circ to the FY19 targer CMMC, ages 15-29 and divides this number by the total male population age 15-29.

CORRECTION: =IFERROR((EV7+EY7)/EN7,0)

**Comment by achafetz** [comment]
will try to look at this tomorrow during some down time in the schedule.

**Comment by achafetz** [comment]
Correct on all counts. Fixed and adding to the Change Log.
