### ISSUE TITLE
E Weathers: Potential Formula Error: SNU Targets Tab, "FY19 Target KP_PREV PWID Male (Denom)"

### ISSUE THREAD

**Issue by annakradin** [achafetz/DataPack#131]
SNU Targets tab, the formula in the " FY19 Target KP_PREV PWID Male (Denom.)" column DE produces a #NAME? error. The index match formula references kp_prev_pwid_D_fy19
SOLUTION: The correct reference should be kp_prev_pwid_M_D_fy19

**Comment by achafetz** [comment]
already identified and fixed
