### ISSUE TITLE
E Weathers: Potential error in column headings: Allocation by SNUxIM tab, columns DJ and DK

### ISSUE THREAD

**Issue by annakradin** [achafetz/DataPack#133]
Allocation by SNUxIM tab, columns DJ and DK [KP_PREV People in prisons & other closed settings (Denom.)]. The heading for both say Denom. 
SOLUTION: I believe column heading should read:
DJ: KP_PREV People in prisons & other closed settings (Denom.)
DK: KP_PREV People in prisons & other closed settings

**Comment by achafetz** [comment]
Fixed in template and adding to change log
