### ISSUE TITLE
E Weathers: Potential formula error: Target Calculation Tab, "FY19 Target OVC_SERV <18"

### ISSUE THREAD

**Issue by annakradin** [achafetz/DataPack#134]
Target Calculation tab, the formula in the "FY19 Target OVC_SERV <18" column HC references column GA for the denominator when calculating target [=IFERROR(HB7*GA7,"")]. Column GA is the FY17 OVC_SERV result.  The datapack manual says the " FY19 Target OVC_SERV <18" target is based on "FY19 Target OVC_SERV".
SOLUTION: Change the formula to =IFERROR(HB7*GX7,"")

**Comment by achafetz** [comment]
Just fixed in the template and added to the change log
