### ISSUE TITLE
Formatting in Malawi non-HTS Disag tool

### ISSUE THREAD

**Issue by pvinayak001** [achafetz/DataPack#136]
Filename: MalawiCOP18DisaggToolv2018.01.30
PMTCT_STAT: Inconsistent formula error (green triangle) showing for Columns BH-BO
TB_STAT: Columns U-AA formatted yellow

**Comment by achafetz** [comment]
Yeah, I can't figure out how to get rid of it. You'll note that the first row is fine.

I might try on the next batch to change the error checking in Excel and see if that carries over across users.

**Comment by achafetz** [comment]
![image](https://user-images.githubusercontent.com/8933069/35927733-6b113a96-0bf9-11e8-9df6-d2c08935fd75.png)

**Comment by achafetz** [comment]
Didn't implement
