### ISSUE TITLE
Negative targets in Malawi non-HTS disag tool

### ISSUE THREAD

**Issue by pvinayak001** [achafetz/DataPack#140]
Negative targets showing for OVC_SERV, columns BT, CJ-CM (Age/Sex 18+)

**Comment by achafetz** [comment]
Seems concerning, but this is a result of not having total numerator targets entered in the data pack, not a formula issue. If negative numbers are showing up in the disagg tool, it's clear the country team missed a step or two along the way.

**Comment by bowdenj** [comment]
Hey @achafetz - know you closed this, but one follow-up question: I'm seeing this in Zambia as well when I copy/pasted their data pack. It looks like every negative target so far is associated with a mechanism ID of 0. Is it expected that country teams would fix any mechanisms with an ID of 0 before submitting their data packs?

**Comment by achafetz** [comment]
I assume you're looking at the Assumption by SNUxIM tab. This will have negative numbers for all dedeup mechanism (0). Dedup mechanism don't show up on any of the indicator tabs.

The negative targets @pvinayak001 is referring to are where you have a missing numerator (eg OVC_SERV) but a <15/18 disagg (eg OVC_SERV <18) which then creates a negative adult target. Once a country completes the data pack, there will be no missing total numerators and this issue will not exist.

**Comment by bowdenj** [comment]
Of course--that makes sense--thanks, Aaron.
