### ISSUE TITLE
Sum of <15 Fine Age Disagg Targets Not Always Equal to <15 Target Col AC

### ISSUE THREAD

**Issue by bowdenj** [achafetz/DataPack#143]
Hi @achafetz -Do fine disagg targets include any kind of rounding? This may not be an issue, but I'm finding a handful of instances where a sum of the fine <15 age disagg columns does not equal the total <15 target. 

I'm specifically looking at Zambia's TX_CURR tab. The sum of the Age/Sex/HIVStatus <15 disaggregates (columns AE-AH) does not always equal the number in the TX_CURR <15 target column (AC). However, the difference never appears to be greater than 1. 

An example includes Chibombo District MechID 17399. Sum of fine age disaggs <15 = 37; <15 TX_CURR target = 38. that pattern of the sum of fine disaggs being a little less is repeated a few other times throughout the SNU/IMs. 

The only place where it appears to be more than a rounding error (more than 1) is in Chongwe District MechID 13580. Sum of fine age disaggs <15 = 1136; TX_CURR <15 target = 1138.

There is a much larger discrepancy for the 15+ age bands, but I'm assuming this has to do with the five-year age bands for 15+ not being filled in yet, as discussed in our earlier meeting.

**Comment by achafetz** [comment]
Thanks, @bowdenj. Yes, this is all due to rounding. I have added a validation to see if the allocation total sums to 100% in the newer version.  I will also add additional decimal places to help with that rounding issue.
