### ISSUE TITLE
"Unhealthy" Workspace?

### ISSUE THREAD

**Issue by achafetz** [achafetz/DataPack#148]
Populating Disagg Tools is running extremely slowly on the server. VBA processes a very vague error at the end of the finishing a tool ("Automation error exception occurred") so can only run one at a time, prior to Excel crashing.

Restarted the AWS and got the error message below. Able to log back in after a few minutes, but didn't know if the status of the workspacing being "unhealthy" is concerning.

![screen shot 2018-02-10 at 3 00 44 pm](https://user-images.githubusercontent.com/8933069/36066176-a3bd43d6-0e73-11e8-9fcc-bbfbe8a67773.png)

**Comment by jacksonsj** [comment]
I contacted Dan Cocos for support. Will let you know. See below for preliminary answer:

![image](https://user-images.githubusercontent.com/31488407/36066240-7a62b150-0e74-11e8-9334-bc9a2c0899b0.png)

**Comment by achafetz** [comment]
thnaks.

probably related to "High CPU utilization." Hopefully the restart helped

**Comment by jacksonsj** [comment]
Did you restart it or does it need someone to do that for you?

**Comment by jacksonsj** [comment]
Also, please add Dan Cocos to this repo so he can be looped in to this ticket

**Comment by achafetz** [comment]
It appears I have privileges to restart, and am up and running again. 

Sent an invite to Dan and can tag him when he accepts the invite.

thanks!

**Comment by jacksonsj** [comment]
Great. Keep me posted if you encounter anything else. Happy to help triage issues to the right people.

**Comment by achafetz** [comment]
Haven't run into this issue again
