### ISSUE TITLE
Schlenker notes issue with OVC_SERV in DATIM Indicator Table in Uganda Datapack

### ISSUE THREAD

**Issue by annakradin** [achafetz/DataPack#158]
From Kristy Schlenker: Sorry to be the bearer of continued bad news everyone! It looks like our OVC_SERV historical data is still off in the new DATIM Indicator Table tab too. It shows Uganda has over 1 million OVC_SERV as the FY17 APR value. The true value is approximately (but not exactly) half that. I haven't checked the OVC_SERV disaggs again this time, but it would be appreciated if someone could help to confirm whether or not those also need correcting.
 
Thanks,
 
Kristy

**Comment by achafetz** [comment]
Duplicate of #154
