### ISSUE TITLE
gather cluster information

### ISSUE THREAD

**Issue by achafetz** [achafetz/DataPack#2]
PSNUs associated in cluster & breakdown percentages (needed for DATIM import)

[FY17 Clustered PSNU List](https://github.com/achafetz/DataPack/blob/master/RawData/COP17Clusters.csv)

required inputs + % of targets:

psnu | psnuuid | fy17snuprioritization | cluster_psnu | cluster_snu1 | cluster_psnuuid | cluster_fy17snuprioritization | cluster_set | cluster_submitter
-- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by achafetz** [comment]
consolidated guidance to go out soon(?) with a due date of Dec 8

**Comment by achafetz** [comment]
need to work to figure out standardized cluster naming convention that need to be unique globally.

associated with COP Target setting Setting [issue 43](https://github.com/pepfar-datim/COP18-Target-Setting/issues/43)

**Comment by achafetz** [comment]
@jason-p-pickering is there character limit for orgunit names? trying to think about rules around cluster names (for standardization) and noticed TNZ has a cluster named "Dar es Salaam-Bagamoyo-Kisarawe-Kibaha-Mkuranga Cluster" which is 55 characters.

to standardize, I think all cluster will look like:  Greater Francistown Cluster (BWA) --> [cluster name] Cluster ([country iso code])

**Comment by jason-p-pickering** [comment]
@achafetz there is, and there are some additional requirements. 

1) "Names" must be less than 230 characters
2) Short names must be less than 50 characters
3) A code is not required, but should be less than 50 characters as well. 


To keep things simple ,if you could make all names 50 characters or less, then we could make the name and short name the same. 

Also, keep in mind that names, shortnames and codes must be globally unique.

**Comment by achafetz** [comment]
Thanks. Only one cluster name exceeds this and other are not close. We can address this and standardizing  probably in Dec.


rank | cluster name characters
-- | --
1 | 55
2 | 36
3 | 35
4 | 30
5 | 30
