### ISSUE TITLE
figure out duplicate PSNUs

### ISSUE THREAD

**Issue by achafetz** [achafetz/DataPack#36]
last year, there were a number of psnus found to be duplicates (but with a different `psnuuid`). @noahbartlett went through to clean up the the list. A similar list exists this year to be reviewed. Is it possible for the three countries (Burma, Ghana, and Nigeria) to clean up their hierarchy?

[code used to identify duplicates can be found here](https://github.com/achafetz/ICPI_Projects/blob/master/Other/dupSNUs.do)

adjusted during data pack creation process in ~~[06_datapack_dup_snus.do](https://github.com/achafetz/DataPack/blob/master/Archive/COP17/DoFiles/06_datapack_dup_snus.do)~~  [06_datapack_snu_adj.R](https://github.com/achafetz/DataPack/blob/master/Scripts/06_datapack_snu_adj.R)

linked to #41 

duplicates list

| operatingunit | psnu                    | psnuuid     | FY16 action         | FY17 action |
|---------------|-------------------------|-------------|---------------------|-------------|
| Burma         | Dagon Myothit (Seikkan) | Z6b0Advh1f8 | N/A                 | Combine |
| Burma         | Dagon Myothit (Seikkan) | qPyHEwO7X6D | N/A                 | Combine |
| Ghana         | Jomoro                  | dASd72VnJPh | Combine             | Keep |
| Ghana         | Jomoro                  | dOQ8r7iwZvS | Combine             | Delete (Blank)|
| Nigeria       | eb Abakaliki            | EzsXkY9WARj | Combine             | Combine|
| Nigeria       | eb Abakaliki            | URj9zYi533e | Combine             | Combine |
| Nigeria       | eb Afikpo North         | KN2TmcAVqzi | Combine             | Combine         |
| Nigeria       | eb Afikpo North         | bDoKaxNx2Xb | Combine             | Combine|
| Nigeria       | en Enugu South          | HHDEeZbVEaw | Combine             | Delete (Blank)         |
| Nigeria       | en Enugu South          | HhCbsjlKoWA | Combine             | Keep|
| Nigeria       | im Ezinihitte           | IxeWi5YG9lE | Combine             | Delete (Blank)|
| Nigeria       | im Ezinihitte           | dzjXm8e1cNs | Combine             | Keep|
| Nigeria       | im Owerri Municipal     | kxsmKGMZ5QF | Combine             | Combine|
| Nigeria       | im Owerri Municipal     | mVuyipSx9aU | Combine             | Combine         |
| Nigeria       | im Owerri North         | FjiNyXde6Ae | Combine             | Combine         |
| Nigeria       | im Owerri North         | xmRjV3Gx1H6 | Combine             | Combine|
| Nigeria       | ek Ikere                | FLIkT6NShZE | Combine             | Keep       |
| Nigeria       | ek Ikere-Ekiti          | KT3e5pmPdfB | Combine             | Delete (Blank)       |
| Nigeria       | eb Ebonyi               | J4yYjIqL7mG | Keep                | Combine|
| Nigeria       | eb Ebonyi               | oygNEfySnMl | Delete (Blank)      | Combine|
| Nigeria       | en Enugu East           | HlABmTwBpu6 | Keep                | Keep |
| Nigeria       | en Enugu East           | h61xiVptz4A | Delete (Duplicates) | Delete (Blank) |
| Nigeria       | en Nsukka               | ITdnyCiBvz7 | Keep                | Keep|
| Nigeria       | en Nsukka               | lC1wneS1GR5 | Delete (Duplicates) | Delete (Blank)|
| Nigeria       | im Ngor Okpala          | vpCKW3gWNhV | Keep                | Keep|
| Nigeria       | im Ngor Okpala          | D47MUIzTapM | Delete (Duplicates) | Delete (Blank)|
| Haiti | Vallières  | RVzTHBO9fgR | | Delete (Blank)|
| Haiti | Vallières  | ONUWhpgEbVk | | Keep|
| India | Chandigarh | rdZgJxh6GA6 |  | No FY17 data|
| India | Chandigarh | eknq1Uf5JK6 | |  No FY17 data|

**Comment by noahbartlett** [comment]
Made a determination on all pairs.
