### ISSUE TITLE
Create configuration file

### ISSUE THREAD

**Issue by jason-p-pickering** [achafetz/DataPack#43]
https://github.com/achafetz/DataPack/blob/master/DoFiles/00_datapack_initialize.R#L17

replace with a configuration file which can be read by the scripts and not depend on redoing this in the code. 

I can assist with this @achafetz .

**Comment by achafetz** [comment]
Thanks, @jason-p-pickering. I'll do some homework on this and probably reach out to you early next week.

**Comment by jason-p-pickering** [comment]
Consider using `jsonlite` to define local configuration files which would be  independent of the execution environment.

**Comment by achafetz** [comment]
didn't implement
