### ISSUE TITLE
PMTCT_ARV on ART creation

### ISSUE THREAD

**Issue by achafetz** [achafetz/DataPack#62]
What should go into FY17 PMTCT_ARV On ART?
--> PMTCT_ART  & all of NewExistingArt (Life-long ART New & Life-long ART Already)?

pmtct_art_already = Life-long ART Already (last year)
pmtct_art_curr = Life-long ART New and Triple-drug ARV (last year)
in targeting tab, FY17 PMTCT_ART = pmtct_art_aready + pmtct_art_curr

![image](https://user-images.githubusercontent.com/8933069/33464504-8dfae346-d610-11e7-9674-48169b4ed9a0.png)

**Comment by achafetz** [comment]
@KatieOC, any insights here?

**Comment by KatieOC** [comment]
FY17 PMTCT_ART = indicator PMTCT_ART (disagg TOTAL Numerator). I've never seen PMTCT_ART_CURR before. DATIM auto-calculates the disaggregated by regimen (new on art + already on art) to give us the numerator.

**Comment by achafetz** [comment]
Thanks! I think last year we didn't have the combined ART numerator (?) output in the FV and aded up New and Already on ART (which I dubbed curr) to get the ART. I'll just use the total numerator this year.
