### ISSUE TITLE
PMTCT_STAT Denominator

### ISSUE THREAD

**Issue by achafetz** [achafetz/DataPack#63]
no PMTCT_STAT `Total Denominator` in FY18 . `Age` in FY2017 APR is equal to `Total Denominator`, so can I use that, @KatieOC?

```
fv %>% 
  filter(indicator == "PMTCT_STAT", numeratordenom == "D") %>%
  group_by(disaggregate) %>% 
  summarise_at(vars(fy2017apr, fy2018_targets), funs(sum(., na.rm = TRUE)))
```

**Comment by KatieOC** [comment]
yes correct, the finer age bands auto-sum to give us the denominator. This may apply to your earlier question if you can't access the disaggregate "total numerator" or "total denominator" but the fact view dataset does have this info. indicator = PMTCT_STAT, numeratorDenom = D and disaggregate = TotalDenominator. Does that help?

**Comment by achafetz** [comment]
Excellent. Just wanted to make sure. I'll roll up `Age` for use as the `Total Numerator` for the FY18 Target
