### ISSUE TITLE
PMTCT_EID FY18 Total Numerator

### ISSUE THREAD

**Issue by achafetz** [achafetz/DataPack#64]
@KatieOC, one more for you, there is no `Total Numerator` for PMTCT_EID in FY18 targets. Can I use `Age/HIVStatus` since FY17 appears to mirror `Total Numerator`?

```
fv %>% 
  filter(indicator == "PMTCT_EID") %>%
  group_by(disaggregate) %>% 
  summarise_at(vars(fy2017apr, fy2018_targets), funs(sum(., na.rm = TRUE)))
```

**Comment by KatieOC** [comment]
No, age/HIVStatus should be retired I think and I believe we just saw Kenya use it. Infant test should be the right one but Lesotho and Kenya are missing values for FY17 targets, not sure if that applies to FY18 targets as well.

**Comment by achafetz** [comment]
Looks like `InfantTest` is being retired. Need to use `Age/HIVStatus` moving forward.
