### ISSUE TITLE
FY19 PMTCT_STAT denominator

### ISSUE THREAD

**Issue by achafetz** [achafetz/DataPack#68]
L.Tally -   PMTCT (Column BG): Recommend that default PMTCT_STAT denominator be FY17 results rather than FY18 targets. Likely more realistic [Not a big deal to leave as is though].

What do you think, @KatieOC?

![image](https://user-images.githubusercontent.com/8933069/34042657-65b37488-e1a6-11e7-9dbd-9f8288bd72f6.png)

**Comment by KatieOC** [comment]
@achafetz I concur with Leigh.

**Comment by achafetz** [comment]
many thanks!
