### ISSUE TITLE
PMTCT_EID age disaggs - Data Pack or Disagg Tool

### ISSUE THREAD

**Issue by achafetz** [achafetz/DataPack#70]
L.Tally - PMTCT_EID: Since this target will likely need to be disaggregated by age at testing (<=2 months and 2-12 months), can this be incorporated into the datapack? The PMTCT group already recommended certain %s as default (I think). Possibly...? 

me - We will have a disaggregation tool which contains all disaggregation for every indicator not calculated in the data pack. If it makes sense to use an assumption for all countries, I would say maybe the data pack is the way to go; if its based on historic distribution, as I'm currently anticipating.

@KatieOC, would it be better to prescribe a percent breakdown for every country or use historic (FY17 APR) data?

**Comment by KatieOC** [comment]
@achafetz  we do highly recommend that their EID 0-2 months be 80% of their overall target.

**Comment by KatieOC** [comment]
@achafetz target for PMTCT_EID 12 month, do you have 95% of PMTCT_STAT_POS as the denominator or are you using results from last year? I can't remember. Last year I think you did 95% which I agree with.

**Comment by achafetz** [comment]
okey doke! done. 

and yes, we use 95% of FY19 Target PMTCT_STAT_POS number of HIV-positive pregnant women
