### ISSUE TITLE
Assumptions: PLHIV <15 question

### ISSUE THREAD

**Issue by KatieOC** [achafetz/DataPack#79]
Columns J and K are set to =I. Is this what you were intending since column I is taking a certain percentage of column F. Wouldn't column J take certain percentage of  column G, etc? Asking in case this is a formula issue or if this was a intentional. 

![image](https://user-images.githubusercontent.com/34076296/34173598-f9b57378-e4c3-11e7-8bca-5deaa9e41015.png)

**Comment by achafetz** [comment]
Intentional. We only have FY17 PLHIV in NAT_SUBNAT so we just take it as a flatline. Countries should adjust based on their PLHIV data.
