### ISSUE TITLE
DATIM Indicator Table- VMMC Section

### ISSUE THREAD

**Issue by Yabayabadoo** [achafetz/DataPack#80]
FY17 VMMC_CIRC[cols: FE & FF): values are the same for vmmc_circ_pos and vmmc_circ_neg.

![image](https://user-images.githubusercontent.com/34660366/34173923-17341af2-e4c5-11e7-80b3-edc9931e4346.png)

**Comment by achafetz** [comment]
Missing the resultstatus [Posivitive/Negative] in the indicator calculation. Add it in.

![image](https://user-images.githubusercontent.com/8933069/34174312-7f8078d4-e4c6-11e7-98b2-22021ecb9a69.png)

**Comment by KTmonkey** [comment]
I want to add to this ticket please. Col FD in many cases is identical to FE and FF...I would think it would be different. Please verify :)
