### ISSUE TITLE
Anticipated achievement of FY18 TX_CURR target >> In general percents in Total row

### ISSUE THREAD

**Issue by HosseiniPR** [achafetz/DataPack#81]
Target Calculation, Column AA, Anticipated achievement of FY18 TX_CURR target

Suggestion that this have "=AB5/Z5" formula, so that you can see percent achievement overall . Perhaps also highlight if this is not 100% #

**Comment by HosseiniPR** [comment]
Likewise, =AF5/AD5 in Column AE, Percent of eligible followed into cohort
Likewise, =AH5/AF5, in Column AG, 12 mo Treatment Retention Rate: Newly Enrolled

**Comment by achafetz** [comment]
These are all set in the assumptions tab, based on a predefined value.
