### ISSUE TITLE
Assumption Input- Percentage of OVC Grad/Transferred/Exited

### ISSUE THREAD

**Issue by Yabayabadoo** [achafetz/DataPack#87]
Change denominator of calculation to represent OVC <18 yo instead of OVC_SERV total?

![image](https://user-images.githubusercontent.com/34660366/34174672-b6002dd6-e4c7-11e7-8003-2ddc6f774e5a.png)

**Comment by shapaklyak** [comment]
I think the revised process for setting FY19 targets was that this be under all OVC_SERV not just under 18. Checking w/Christine , will follow-up w @achafetz @Yabayabadoo

**Comment by shapaklyak** [comment]
@achafetz @Yabayabadoo **"Yes, the targets are for all ages**. We need a separate tool for targets for age/sex, which Aaron said he was working on. "  per Christine.

**Comment by achafetz** [comment]
to confirm, there is no change since this is currently using total not <18.
