### ISSUE TITLE
PMTCT_STAT and STAT_POS (Indicator Table)

### ISSUE THREAD

**Issue by victoriadryan** [achafetz/DataPack#88]
FY17 PMTCT_STAT POS and FY17 PMTCT_STAT Known positives at entry are displaying values of zero. Will check scripts to see if can figure out the issue.
![image](https://user-images.githubusercontent.com/18488502/34174678-bb9d28c0-e4c7-11e7-86ff-52990c108bde.png)

**Comment by achafetz** [comment]
issue with some (all?) positives was that the calculation was `age = "Positive"`. Fixed to now be correct - `resultstatus = "Positive"`
