### ISSUE TITLE
Assumption Input tab (Kenya): TX_RET yield reference calculation

### ISSUE THREAD

**Issue by imujawar** [achafetz/DataPack#91]
The TX_RET yield reference calculation from the DATIM Indicator tab calculates estimated yield as 100% when the Numerator and Denominator are zero. 

![image](https://user-images.githubusercontent.com/18144056/34174820-4971fc66-e4c8-11e7-8556-f63921853b69.png)

![image](https://user-images.githubusercontent.com/18144056/34174852-5f19cc2e-e4c8-11e7-87e5-929ca5ab96b1.png)

@achafetz

**Comment by achafetz** [comment]
adjusted VBA code to resolve.
