### ISSUE TITLE
Allocation by SNUXIM Tab

### ISSUE THREAD

**Issue by KTmonkey** [achafetz/DataPack#97]
Col CL for VMMC % distribution is not populating correctly. Please correct this and make sure that Col GX is then populating correctly. 

This error is also affecting FL and FM on the IM summary tab as well. Please make sure they get straightened out as well.

**Comment by achafetz** [comment]
issue due to a misalignment of the data created out of R and the columns in the allocation tab (eg TX_CURR <15 was missing along with a handful of other indicators.
