### ISSUE TITLE
Target Calculation - OVC_SERV FY17 Results

### ISSUE THREAD

**Issue by shapaklyak** [achafetz/DataPack#99]
FY17 Results by participation/program status are flipped - See Homa Bay example, results under Transferred (column FO) is actually ACTIVE, and results under Active (column FQ) is actually TRANSFERRED. 
 
![image](https://user-images.githubusercontent.com/5234106/34175574-e2795d26-e4ca-11e7-8d4a-ac0c426bfe06.png)

![image](https://user-images.githubusercontent.com/5234106/34175582-ed9a52e6-e4ca-11e7-8585-9522780e78e3.png)

**Comment by shapaklyak** [comment]
Formula update..

![image](https://user-images.githubusercontent.com/5234106/34175939-2c985a00-e4cc-11e7-91f3-f9c889ce9f55.png)

**Comment by achafetz** [comment]
Fixed!
